env:
  es2021: true
  node: true
extends:
  airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - jest
rules: 
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 0
  no-console: 0

