env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
}
